import 'package:flutter/cupertino.dart';

class Trans {
  static final Trans _singleton = Trans._internal(Locale("en"));

  Locale locale;

  factory Trans() {
    return _singleton;
  }

  Trans._internal(this.locale);

  String get checkingForNewVersion => _localizedValues[locale.languageCode]!['checkingForNewVersion']!;

  String get newVersionIsAvailable => _localizedValues[locale.languageCode]!['newVersionIsAvailable']!;

  String get pleaseUpdateNow => _localizedValues[locale.languageCode]!['pleaseUpdateNow']!;

  String get updateNow => _localizedValues[locale.languageCode]!['updateNow']!;

  String get changes => _localizedValues[locale.languageCode]!['changes']!;

  String get downloadUpdate => _localizedValues[locale.languageCode]!['downloadUpdate']!;

  String get couldNotLaunch => _localizedValues[locale.languageCode]!['couldNotLaunch']!;

  static Trans of(BuildContext context) {
    //Change locale from System, App Preferences or other variables.
    return _singleton;
  }

  static Map<String, Map<String, String>> _localizedValues = {
    'af': {
      "newVersionIsAvailable": "Nuwe weergawe is beskikbaar",
      "changes": "Veranderings",
      "downloadUpdate": "Laai opdatering af",
      "pleaseUpdateNow": "Werk u aansoek nou op!",
      "checkingForNewVersion": "Soek tans vir nuwe weergawe ...",
      "couldNotLaunch": "Kon nie begin nie",
      "updateNow": "Nou op datum bring" },
    'ar': {
      "newVersionIsAvailable": "الإصدار الجديد متاح",
      "changes": "التغييرات",
      "downloadUpdate": "حمل التحديث",
      "pleaseUpdateNow": "من فضلك ، قم بتحديث التطبيق الخاص بك الآن!",
      "checkingForNewVersion": "جاري البحث عن إصدار جديد ...",
      "couldNotLaunch": "تعذر الإطلاق",
      "updateNow": "تحديث الان" },
    'az': {
      "newVersionIsAvailable": "Yeni versiya mövcuddur",
      "changes": "Dəyişikliklər",
      "downloadUpdate": "Yeniləməni yükləyin",
      "pleaseUpdateNow": "Zəhmət olmasa, tətbiqinizi yeniləyin, indi!",
      "checkingForNewVersion": "Yeni versiya yoxlanılır ...",
      "couldNotLaunch": "Başlamaq alınmadı",
      "updateNow": "İndi yeniləyin" },
    'be': {
      "newVersionIsAvailable": "Даступная новая версія",
      "changes": "Змены",
      "downloadUpdate": "Спампаваць абнаўленне",
      "pleaseUpdateNow": "Калі ласка, абнавіце вашу заяўку, зараз!",
      "checkingForNewVersion": "Праверка новай версіі ...",
      "couldNotLaunch": "Не атрымалася запусціць",
      "updateNow": "Абнавіць зараз" },
    'bg_BG': {
      "newVersionIsAvailable": "Налична е нова версия",
      "changes": "Промени",
      "downloadUpdate": "Изтеглете актуализацията",
      "pleaseUpdateNow": "Моля, актуализирайте приложението си сега!",
      "checkingForNewVersion": "Проверка за нова версия ...",
      "couldNotLaunch": "Не може да се стартира",
      "updateNow": "Актуализирайте сега" },
    'bg': {
      "newVersionIsAvailable": "Налична е нова версия",
      "changes": "Промени",
      "downloadUpdate": "Изтеглете актуализацията",
      "pleaseUpdateNow": "Моля, актуализирайте приложението си сега!",
      "checkingForNewVersion": "Проверка за нова версия ...",
      "couldNotLaunch": "Не може да се стартира",
      "updateNow": "Актуализирайте сега" },
    'bn': {
      "newVersionIsAvailable": "নতুন সংস্করণ উপলব্ধ",
      "changes": "পরিবর্তন",
      "downloadUpdate": "আপডেট ডাউনলোড করুন",
      "pleaseUpdateNow": "দয়া করে এখনই আপনার আবেদন আপডেট করুন!",
      "checkingForNewVersion": "নতুন সংস্করণ অনুসন্ধান করা হচ্ছে ...",
      "couldNotLaunch": "আরম্ভ করা যায়নি",
      "updateNow": "এখন হালনাগাদ করুন" },
    'ca': {
      "newVersionIsAvailable": "Hi ha disponible una nova versió",
      "changes": "Canvis",
      "downloadUpdate": "Descarregar actualització",
      "pleaseUpdateNow": "Actualitzeu la vostra sol·licitud ara.",
      "checkingForNewVersion": "S&#39;està cercant la nova versió ...",
      "couldNotLaunch": "No s&#39;ha pogut iniciar",
      "updateNow": "Actualitzar ara" },
    'cs': {
      "newVersionIsAvailable": "Je k dispozici nová verze",
      "changes": "Změny",
      "downloadUpdate": "Stáhnout aktualizaci",
      "pleaseUpdateNow": "Aktualizujte prosím svou aplikaci hned teď!",
      "checkingForNewVersion": "Kontrola nové verze ...",
      "couldNotLaunch": "Nelze spustit",
      "updateNow": "Nyní aktualizovat" },
    'da': {
      "newVersionIsAvailable": "Ny version er tilgængelig",
      "changes": "Ændringer",
      "downloadUpdate": "Download opdatering",
      "pleaseUpdateNow": "Venligst opdater din ansøgning nu!",
      "checkingForNewVersion": "Søger efter ny version ...",
      "couldNotLaunch": "Kunne ikke starte",
      "updateNow": "Opdatere nu" },
    'de': {
      "newVersionIsAvailable": "Neue Version ist verfügbar",
      "changes": "Änderungen",
      "downloadUpdate": "Aktualisierung herunterladen",
      "pleaseUpdateNow": "Bitte aktualisieren Sie Ihre Anwendung jetzt!",
      "checkingForNewVersion": "Suche nach neuer Version ...",
      "couldNotLaunch": "Konnte nicht starten",
      "updateNow": "Jetzt aktualisieren" },
    'el': {
      "newVersionIsAvailable": "Η νέα έκδοση είναι διαθέσιμη",
      "changes": "Αλλαγές",
      "downloadUpdate": "Λήψη ενημέρωσης",
      "pleaseUpdateNow": "Παρακαλώ, ενημερώστε την αίτησή σας, τώρα!",
      "checkingForNewVersion": "Έλεγχος για νέα έκδοση ...",
      "couldNotLaunch": "Δεν ήταν δυνατή η εκκίνηση",
      "updateNow": "Ενημέρωση τώρα" },
    'en_US': {
      "newVersionIsAvailable": "New Version is Available",
      "changes": "Changes",
      "downloadUpdate": "Download Update",
      "pleaseUpdateNow": "Please, Update your Application, Now!",
      "checkingForNewVersion": "Checking for new Version ...",
      "couldNotLaunch": "Could not launch",
      "updateNow": "Update Now" },
    'en': {
      "newVersionIsAvailable": "New Version is Available",
      "changes": "Changes",
      "downloadUpdate": "Download Update",
      "pleaseUpdateNow": "Please, Update your Application, Now!",
      "checkingForNewVersion": "Checking for new Version ...",
      "couldNotLaunch": "Could not launch",
      "updateNow": "Update Now" },
    'es_ES': {
      "newVersionIsAvailable": "Nueva versión disponible",
      "changes": "Cambios",
      "downloadUpdate": "Descarga de la actualización",
      "pleaseUpdateNow": "¡Actualice su aplicación ahora!",
      "checkingForNewVersion": "Buscando nueva versión ...",
      "couldNotLaunch": "No se pudo iniciar",
      "updateNow": "Actualizar ahora" },
    'es': {
      "newVersionIsAvailable": "Nueva versión disponible",
      "changes": "Cambios",
      "downloadUpdate": "Descarga de la actualización",
      "pleaseUpdateNow": "¡Actualice su aplicación ahora!",
      "checkingForNewVersion": "Buscando nueva versión ...",
      "couldNotLaunch": "No se pudo iniciar",
      "updateNow": "Actualizar ahora" },
    'et': {
      "newVersionIsAvailable": "Uus versioon on saadaval",
      "changes": "Muutused",
      "downloadUpdate": "Laadige alla värskendus",
      "pleaseUpdateNow": "Palun värskendage oma rakendust kohe!",
      "checkingForNewVersion": "Uue versiooni otsimine ...",
      "couldNotLaunch": "Ei saanud käivitada",
      "updateNow": "Uuendage kohe" },
    'eu': {
      "newVersionIsAvailable": "Bertsio berria eskuragarri dago",
      "changes": "Aldaketak",
      "downloadUpdate": "Deskargatu eguneratzea",
      "pleaseUpdateNow": "Mesedez, eguneratu eskaera, orain!",
      "checkingForNewVersion": "Bertsio berria bilatzen ...",
      "couldNotLaunch": "Ezin izan da abiarazi",
      "updateNow": "Eguneratu orain" },
    'fi': {
      "newVersionIsAvailable": "Uusi versio on saatavana",
      "changes": "Muutokset",
      "downloadUpdate": "Lataa päivitys",
      "pleaseUpdateNow": "Päivitä sovelluksesi nyt!",
      "checkingForNewVersion": "Tarkistetaan uutta versiota ...",
      "couldNotLaunch": "Ei voitu käynnistää",
      "updateNow": "Päivitä nyt" },
    'fr': {
      "newVersionIsAvailable": "Une nouvelle version est disponible",
      "changes": "Changements",
      "downloadUpdate": "Télécharger la mise à jour",
      "pleaseUpdateNow": "S'il vous plaît, mettez à jour votre application, maintenant !",
      "checkingForNewVersion": "Recherche d&#39;une nouvelle version...",
      "couldNotLaunch": "Impossible de lancer",
      "updateNow": "Mettez à jour maintenant" },
    'gl': {
      "newVersionIsAvailable": "A nova versión está dispoñible",
      "changes": "Cambios",
      "downloadUpdate": "Descargar actualización",
      "pleaseUpdateNow": "Actualiza a túa solicitude agora!",
      "checkingForNewVersion": "Buscando nova versión ...",
      "couldNotLaunch": "Non se puido iniciar",
      "updateNow": "Actualizar agora" },
    'he': {
      "newVersionIsAvailable": "גרסה חדשה זמינה",
      "changes": "שינויים",
      "downloadUpdate": "להוריד עדכון",
      "pleaseUpdateNow": "אנא, עדכן את היישום שלך, עכשיו!",
      "checkingForNewVersion": "מחפש גרסה חדשה ...",
      "couldNotLaunch": "לא ניתן היה להפעיל",
      "updateNow": "עדכן כעת" },
    'hi': {
      "newVersionIsAvailable": "नया संस्करण उपलब्ध है",
      "changes": "परिवर्तन",
      "downloadUpdate": "अद्यतन डाउनलोड करे",
      "pleaseUpdateNow": "कृपया, अपना आवेदन अपडेट करें, अभी!",
      "checkingForNewVersion": "नए संस्करण की जांच की जा रही है...",
      "couldNotLaunch": "लॉन्च नहीं हो सका",
      "updateNow": "अभी अद्यतन करें" },
    'hr': {
      "newVersionIsAvailable": "Dostupna je nova verzija",
      "changes": "Promjene",
      "downloadUpdate": "Preuzmi ažuriranje",
      "pleaseUpdateNow": "Molimo vas, ažurirajte svoju aplikaciju, odmah!",
      "checkingForNewVersion": "Traženje nove verzije ...",
      "couldNotLaunch": "Nije moguće pokrenuti",
      "updateNow": "Ažurirati sada" },
    'hu': {
      "newVersionIsAvailable": "Új verzió érhető el",
      "changes": "Változtatások",
      "downloadUpdate": "Töltse le a Frissítést",
      "pleaseUpdateNow": "Kérjük, frissítse most az alkalmazását!",
      "checkingForNewVersion": "Új verzió keresése ...",
      "couldNotLaunch": "Nem sikerült elindítani",
      "updateNow": "Frissítse most" },
    'id': {
      "newVersionIsAvailable": "Versi Baru Tersedia",
      "changes": "Perubahan",
      "downloadUpdate": "Unduh Pembaruan",
      "pleaseUpdateNow": "Silakan, Perbarui Aplikasi Anda, Sekarang!",
      "checkingForNewVersion": "Memeriksa Versi baru...",
      "couldNotLaunch": "Tidak dapat diluncurkan",
      "updateNow": "Memperbarui sekarang" },
    'is': {
      "newVersionIsAvailable": "Ný útgáfa er fáanleg",
      "changes": "Breytingar",
      "downloadUpdate": "Sækja uppfærslu",
      "pleaseUpdateNow": "Vinsamlegast uppfærðu umsókn þína núna!",
      "checkingForNewVersion": "Leitar að nýrri útgáfu ...",
      "couldNotLaunch": "Gat ekki ræst",
      "updateNow": "Uppfæra núna" },
    'it': {
      "newVersionIsAvailable": "La nuova versione è disponibile",
      "changes": "I cambiamenti",
      "downloadUpdate": "Scarica aggiornamento",
      "pleaseUpdateNow": "Per favore, aggiorna la tua applicazione, ora!",
      "checkingForNewVersion": "Controllo della nuova versione...",
      "couldNotLaunch": "Impossibile avviare",
      "updateNow": "Aggiorna ora" },
    'ja': {
      "newVersionIsAvailable": "新しいバージョンが利用可能です",
      "changes": "変更点",
      "downloadUpdate": "アップデートをダウンロード",
      "pleaseUpdateNow": "今すぐアプリケーションを更新してください！",
      "checkingForNewVersion": "新しいバージョンを確認しています...",
      "couldNotLaunch": "起動できませんでした",
      "updateNow": "今すぐアップデート" },
    'kn': {
      "newVersionIsAvailable": "ಹೊಸ ಆವೃತ್ತಿ ಲಭ್ಯವಿದೆ",
      "changes": "ಬದಲಾವಣೆಗಳನ್ನು",
      "downloadUpdate": "ನವೀಕರಣವನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
      "pleaseUpdateNow": "ದಯವಿಟ್ಟು, ನಿಮ್ಮ ಅಪ್ಲಿಕೇಶನ್ ಅನ್ನು ನವೀಕರಿಸಿ, ಈಗ!",
      "checkingForNewVersion": "ಹೊಸ ಆವೃತ್ತಿಯನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ ...",
      "couldNotLaunch": "ಪ್ರಾರಂಭಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ",
      "updateNow": "ಈಗ ನವೀಕರಿಸಿ" },
    'ko': {
      "newVersionIsAvailable": "새 버전을 사용할 수 있습니다.",
      "changes": "변화",
      "downloadUpdate": "업데이트 다운로드",
      "pleaseUpdateNow": "지금 애플리케이션을 업데이트하십시오!",
      "checkingForNewVersion": "새 버전 확인 중 ...",
      "couldNotLaunch": "시작할 수 없습니다",
      "updateNow": "지금 업데이트" },
    'lt': {
      "newVersionIsAvailable": "Yra nauja versija",
      "changes": "Pokyčiai",
      "downloadUpdate": "Atsisiųsti naujinimą",
      "pleaseUpdateNow": "Atnaujinkite savo programą dabar!",
      "checkingForNewVersion": "Tikrinama, ar nėra naujos versijos ...",
      "couldNotLaunch": "Nepavyko paleisti",
      "updateNow": "Atnaujinti dabar" },
    'lv': {
      "newVersionIsAvailable": "Ir pieejama jauna versija",
      "changes": "Izmaiņas",
      "downloadUpdate": "Lejupielādēt atjauninājumu",
      "pleaseUpdateNow": "Lūdzu, atjauniniet savu lietojumprogrammu tūlīt!",
      "checkingForNewVersion": "Tiek meklēta jauna versija ...",
      "couldNotLaunch": "Nevarēja palaist",
      "updateNow": "Atjaunināt tagad" },
    'mk': {
      "newVersionIsAvailable": "Достапна е нова верзија",
      "changes": "Промени",
      "downloadUpdate": "Преземете го ажурирањето",
      "pleaseUpdateNow": "Ве молиме, ажурирајте ја вашата апликација, сега!",
      "checkingForNewVersion": "Се проверува за нова верзија ...",
      "couldNotLaunch": "Не може да се активира",
      "updateNow": "Ажурирање сега" },
    'ml': {
      "newVersionIsAvailable": "പുതിയ പതിപ്പ് ലഭ്യമാണ്",
      "changes": "മാറ്റങ്ങൾ",
      "downloadUpdate": "അപ്‌ഡേറ്റ് ഡൗൺലോഡുചെയ്യുക",
      "pleaseUpdateNow": "ദയവായി, നിങ്ങളുടെ ആപ്ലിക്കേഷൻ അപ്ഡേറ്റ് ചെയ്യുക, ഇപ്പോൾ!",
      "checkingForNewVersion": "പുതിയ പതിപ്പിനായി പരിശോധിക്കുന്നു ...",
      "couldNotLaunch": "സമാരംഭിക്കാനായില്ല",
      "updateNow": "ഇപ്പോൾ തന്നെ നവീകരിക്കുക" },
    'ms': {
      "newVersionIsAvailable": "Versi Baru Terdapat",
      "changes": "Perubahan",
      "downloadUpdate": "Muat turun Kemas kini",
      "pleaseUpdateNow": "Tolong, Kemas kini Permohonan Anda, Sekarang!",
      "checkingForNewVersion": "Memeriksa Versi baru ...",
      "couldNotLaunch": "Tidak dapat dilancarkan",
      "updateNow": "Mengemas kini sekarang" },
    'mt': {
      "newVersionIsAvailable": "Verżjoni Ġdida hija Disponibbli",
      "changes": "Bidliet",
      "downloadUpdate": "Niżżel l-Aġġornament",
      "pleaseUpdateNow": "Jekk jogħġbok, Aġġorna l-Applikazzjoni tiegħek, Issa!",
      "checkingForNewVersion": "Iċċekkjar għal Verżjoni ġdida ...",
      "couldNotLaunch": "Ma setax iniedi",
      "updateNow": "Aġġorna Issa" },
    'nl': {
      "newVersionIsAvailable": "Nieuwe versie is beschikbaar",
      "changes": "Veranderingen",
      "downloadUpdate": "Download update",
      "pleaseUpdateNow": "Werk uw applicatie nu bij!",
      "checkingForNewVersion": "Controleren op nieuwe versie...",
      "couldNotLaunch": "Kan niet starten",
      "updateNow": "Update nu" },
    'no': {
      "newVersionIsAvailable": "Ny versjon er tilgjengelig",
      "changes": "Endringer",
      "downloadUpdate": "Last ned oppdatering",
      "pleaseUpdateNow": "Oppdater søknaden din nå!",
      "checkingForNewVersion": "Ser etter ny versjon ...",
      "couldNotLaunch": "Kunne ikke starte",
      "updateNow": "Oppdater nå" },
    'pl': {
      "newVersionIsAvailable": "Nowa wersja jest dostępna",
      "changes": "Zmiany",
      "downloadUpdate": "Pobierz aktualizację",
      "pleaseUpdateNow": "Zaktualizuj swoją aplikację już teraz!",
      "checkingForNewVersion": "Sprawdzanie nowej wersji...",
      "couldNotLaunch": "Nie można uruchomić",
      "updateNow": "Aktualizuj teraz" },
    'pt': {
      "newVersionIsAvailable": "Nova versão está disponível",
      "changes": "Alterar",
      "downloadUpdate": "Baixar atualização",
      "pleaseUpdateNow": "Por favor, atualize seu aplicativo, agora!",
      "checkingForNewVersion": "Verificando se há uma nova versão ...",
      "couldNotLaunch": "Não foi possível lançar",
      "updateNow": "Atualize agora" },
    'ro': {
      "newVersionIsAvailable": "Noua versiune este disponibilă",
      "changes": "Schimbări",
      "downloadUpdate": "Descărcați actualizarea",
      "pleaseUpdateNow": "Vă rugăm, actualizați aplicația acum!",
      "checkingForNewVersion": "Se verifică versiunea nouă ...",
      "couldNotLaunch": "Nu s-a putut lansa",
      "updateNow": "Actualizează acum" },
    'ru': {
      "newVersionIsAvailable": "Доступна новая версия",
      "changes": "Изменения",
      "downloadUpdate": "Скачать обновление",
      "pleaseUpdateNow": "Пожалуйста, обновите ваше приложение прямо сейчас!",
      "checkingForNewVersion": "Проверка новой версии ...",
      "couldNotLaunch": "Не удалось запустить",
      "updateNow": "Обновить сейчас" },
    'sk': {
      "newVersionIsAvailable": "Je k dispozícii nová verzia",
      "changes": "Zmeny",
      "downloadUpdate": "Stiahnite si aktualizáciu",
      "pleaseUpdateNow": "Aktualizujte si svoju prihlášku hneď teraz!",
      "checkingForNewVersion": "Prebieha kontrola novej verzie ...",
      "couldNotLaunch": "Nepodarilo sa spustiť",
      "updateNow": "Teraz aktualizovať" },
    'sl': {
      "newVersionIsAvailable": "Na voljo je nova različica",
      "changes": "Spremembe",
      "downloadUpdate": "Prenesite posodobitev",
      "pleaseUpdateNow": "Prosimo, posodobite svojo prijavo, zdaj!",
      "checkingForNewVersion": "Preverjanje nove različice ...",
      "couldNotLaunch": "Ne morem zagnati",
      "updateNow": "Posodobi zdaj" },
    'sq': {
      "newVersionIsAvailable": "Versioni i ri është i disponueshëm",
      "changes": "Ndryshimet",
      "downloadUpdate": "Shkarkoni azhurnimin",
      "pleaseUpdateNow": "Ju lutemi, azhurnoni aplikacionin tuaj, tani!",
      "checkingForNewVersion": "Po kontrollon për një version të ri ...",
      "couldNotLaunch": "Nuk mund të nisë",
      "updateNow": "Azhurnoni Tani" },
    'sr': {
      "newVersionIsAvailable": "Доступна је нова верзија",
      "changes": "Промене",
      "downloadUpdate": "Преузми ажурирање",
      "pleaseUpdateNow": "Молимо вас, ажурирајте своју апликацију, одмах!",
      "checkingForNewVersion": "Провера нове верзије ...",
      "couldNotLaunch": "Није могуће покренути",
      "updateNow": "Ажурирање сада" },
    'sv': {
      "newVersionIsAvailable": "Ny version finns tillgänglig",
      "changes": "Ändringar",
      "downloadUpdate": "Ladda ner uppdatering",
      "pleaseUpdateNow": "Snälla, uppdatera din ansökan nu!",
      "checkingForNewVersion": "Söker efter ny version ...",
      "couldNotLaunch": "Det gick inte att starta",
      "updateNow": "Uppdatera nu" },
    'sw': {
      "newVersionIsAvailable": "Toleo Jipya linapatikana",
      "changes": "Mabadiliko",
      "downloadUpdate": "Pakua Sasisho",
      "pleaseUpdateNow": "Tafadhali, Sasisha Maombi yako, Sasa!",
      "checkingForNewVersion": "Inatafuta Toleo jipya ...",
      "couldNotLaunch": "Imeshindwa kuzindua",
      "updateNow": "Sasisha Sasa" },
    'ta': {
      "newVersionIsAvailable": "புதிய பதிப்பு கிடைக்கிறது",
      "changes": "மாற்றங்கள்",
      "downloadUpdate": "புதுப்பிப்பைப் பதிவிறக்குக",
      "pleaseUpdateNow": "தயவுசெய்து, இப்போது உங்கள் விண்ணப்பத்தைப் புதுப்பிக்கவும்!",
      "checkingForNewVersion": "புதிய பதிப்பைச் சரிபார்க்கிறது ...",
      "couldNotLaunch": "தொடங்க முடியவில்லை",
      "updateNow": "இப்பொழுது மேம்படுத்து" },
    'te': {
      "newVersionIsAvailable": "క్రొత్త సంస్కరణ అందుబాటులో ఉంది",
      "changes": "మార్పులు",
      "downloadUpdate": "నవీకరణను డౌన్‌లోడ్ చేయండి",
      "pleaseUpdateNow": "దయచేసి, ఇప్పుడు మీ దరఖాస్తును నవీకరించండి!",
      "checkingForNewVersion": "క్రొత్త సంస్కరణ కోసం తనిఖీ చేస్తోంది ...",
      "couldNotLaunch": "ప్రారంభించలేకపోయాము",
      "updateNow": "ఇప్పుడే నవీకరించండి" },
    'th': {
      "newVersionIsAvailable": "เวอร์ชั่นใหม่มาแล้ว",
      "changes": "การเปลี่ยนแปลง",
      "downloadUpdate": "ดาวน์โหลดอัปเดต",
      "pleaseUpdateNow": "กรุณาอัปเดตใบสมัครของคุณตอนนี้!",
      "checkingForNewVersion": "กำลังตรวจสอบเวอร์ชันใหม่ ...",
      "couldNotLaunch": "เปิดไม่ได้",
      "updateNow": "อัพเดทตอนนี้" },
    'tl': {
      "newVersionIsAvailable": "Magagamit ang Bagong Bersyon",
      "changes": "Mga pagbabago",
      "downloadUpdate": "I-download ang Update",
      "pleaseUpdateNow": "Mangyaring, I-update ang iyong Application, Ngayon!",
      "checkingForNewVersion": "Sinusuri ang bagong Bersyon ...",
      "couldNotLaunch": "Hindi mailunsad",
      "updateNow": "I-update Ngayon" },
    'tr': {
      "newVersionIsAvailable": "Yeni Sürüm Mevcut",
      "changes": "Değişiklikler",
      "downloadUpdate": "Güncellemeyi indir",
      "pleaseUpdateNow": "Lütfen Başvurunuzu Şimdi Güncelleyin!",
      "checkingForNewVersion": "Yeni Sürüm kontrol ediliyor...",
      "couldNotLaunch": "Başlatılamadı",
      "updateNow": "Şimdi güncelle" },
    'uk': {
      "newVersionIsAvailable": "Доступна нова версія",
      "changes": "Зміни",
      "downloadUpdate": "Завантажити оновлення",
      "pleaseUpdateNow": "Оновіть свою заявку, зараз!",
      "checkingForNewVersion": "Перевірка нової версії ...",
      "couldNotLaunch": "Не вдалося запустити",
      "updateNow": "Оновити зараз" },
    'vi': {
      "newVersionIsAvailable": "Phiên bản mới có sẵn",
      "changes": "Những thay đổi",
      "downloadUpdate": "Tải xuống bản cập nhật",
      "pleaseUpdateNow": "Vui lòng cập nhật ứng dụng của bạn ngay!",
      "checkingForNewVersion": "Đang kiểm tra phiên bản mới ...",
      "couldNotLaunch": "Không thể khởi chạy",
      "updateNow": "Cập nhật bây giờ" },
    'zh_CN': {
      "newVersionIsAvailable": "新版本可用",
      "changes": "变化",
      "downloadUpdate": "下载更新",
      "pleaseUpdateNow": "请立即更新您的应用程序！",
      "checkingForNewVersion": "正在检查新版本...",
      "couldNotLaunch": "无法启动",
      "updateNow": "现在更新" },
    'zh_TW': {
      "newVersionIsAvailable": "新版本可用",
      "changes": "變化",
      "downloadUpdate": "下載更新",
      "pleaseUpdateNow": "請立即更新您的應用程序！",
      "checkingForNewVersion": "正在檢查新版本...",
      "couldNotLaunch": "無法啟動",
      "updateNow": "現在更新" }
  };
}
